/*
 * app.h
 *
 *  Created on: Jun 13, 2017
 *      Author: test
 */

#ifndef APP_APP_H_
#define APP_APP_H_

#include "includes.h"

#define PING_PORT_MAX	10

#define PING_PORT_SWITCH_P1		0
#define PING_PORT_BACKROOM		1	// Back Room

#define PING_PORT_SS2			9
#define PING_PORT_SS1			19	// independent

#define PING_PORT_FCT_HOMEPLUG	10

#define VLAN_ALL_LINK		1
#define VLAN_TRUTH_LINK		0

#define DUMY				0

enum relay_chann {
	RLY_DUMMY,
	RLY_DUT_B_SIDE_LINK = 0,

	//Relay board 1,chan1~chan24,

	RLY_GSOM1_UART_RX_1V8,
	RLY_GSOM2_UART_RX_1V8,
	RLY_GSOM1_UART_TX_1V8,
	RLY_GSOM2_UART_TX_1V8,
	RLY_GSOM1_RST_5V_VOLT,
	RLY_GSOM2_RST_5V_VOLT,
	RLY_GSOM1_PWRFAIL_1V8_VOLT,
	RLY_GSOM2_PWRFAIL_1V8_VOLT,

	RLY_BEFORE_POWER_RES,
	RLY_AFTER_POWER_RES,
	RLY_BEFORE_CURRSRC_RES,
	RLY_AFTER_CURRSRC_RES,
	RLY_PWR_FAIL_INT_3V3,
	RLY_14,	///////////////////////////////////
	RLY_PWR_RES_SHORT,
	RLY_SRC_RES_SHORT,

	RLY_FCT_P302B1_RS232IN,
	RLY_FCT_P302B5_RS232IN,
	RLY_3V3_SHIFTER_RS232IN,
	RLY_1V8_SHIFTER_RS232IN,
	RLY_FCT_P302B2_RS232OUT,
	RLY_FCT_P302B4_RS232OUT,
	RLY_3V3_SHIFTER_RS232OUT,
	RLY_1V8_SHIFTER_RS232OUT,

	//Relay board 2,chan25~chan48,

	RLY_SER_SPARE1_RS232IN,
	RLY_SER_SPARE2_RS232IN,
	RLY_SER_SPARE3_RS232IN,
	RLY_SER_ZMODEM_RS232IN,
	RLY_SER_ZM_RTS_RS232IN,
	RLY_DUT_P302A1_RS232IN,
	RLY_DUT_P302A5_RS232IN,
	RLY_DUT_P302B1_RS232IN,

	RLY_DUT_P302B5_RS232IN,
	RLY_I2C_EEP24C02_SDA,
	RLY_I2C_EEP24C02_SCL,
	RLY_DUT_A_SIDE_LINK,		// turn on the relay, A side(0), turn off the relay, B side(1)
	RLY_USB_OVERCURR_3R,
	RLY_38,	///////////////////////////////////
	RLY_SSOM_INSTALLED,		//connect to High Level
	RLY_SER_SPARE1_RS232OUT,

	RLY_SER_SPARE2_RS232OUT,
	RLY_SER_SPARE3_RS232OUT,
	RLY_SER_ZMODEM_RS232OUT,
	RLY_SER_ZM_CTS_RS232OUT,
	RLY_DUT_P302A2_RS232OUT,
	RLY_DUT_P302A4_RS232OUT,
	RLY_DUT_P302B2_RS232OUT,
	RLY_DUT_P302B4_RS232OUT,

	//Relay board 3,chan49~chan72,

	RLY_12V_VOLT = 1,
	RLY_5V_VOLT,
	RLY_3V3_VOLT,
	RLY_2V6_VOLT,
	RLY_1V3_VOLT,
	RLY_1V05_VOLT,
	RLY_1V8C_VOLT,
	RLY_1V8X_VOLT,

	RLY_LP_DUT_P303_1_FCT_P300_5,
	RLY_LP_DUT_P303_2_FCT_P300_4,
	RLY_LP_DUT_P300_1_FCT_P303_2,
	RLY_LP_DUT_P300_3_FCT_P303_1,
	RLY_LP_DUT_P300_4_FCT_P303_2,
	RLY_LP_DUT_P300_5_FCT_P303_1,
	RLY_LP_DUT_P333_3_FCT_P303_2,
	RLY_LP_DUT_P333_4_FCT_P303_1,

	RLY_LP_DUT_P300_3_REVERSE,
	RLY_LP_DUT_P300_1_REVERSE,
	RLY_LP_DUT_P300_5_REVERSE,
	RLY_LP_DUT_P300_4_REVERSE,
	RLY_HOME_PLUG_2W_1,
	RLY_HOME_PLUG_2W_2,
	RLY_I2C_PCA9537_SDA,
	RLY_I2C_PCA9537_SCL,

	//Relay board 4,chan73~chan96,

	RLY_CURRSRC_34MA,
	RLY_CURRSRC_45MA,
	RLY_DUT_LOAD_10R_IN_PUMP,
	RLY_JUMPER_J5_VLAN,
	RLY_JUMPER_J4_MODE,
	RLY_JUMPER_J3_HP_BR,
	RLY_JUMPER_J12_SMTCRD,
	RLY_MIIMUX_WD_PULLLO,

	RLY_MIIMUX_WD_ASSERT,	// normal up pull, relay on to GND
	RLY_ACTIVE_WD_ASSERT,
	RLY_ACTIVE_WD_PULLHI,
	RLY_SEPORT_SPARE1_LOOP,
	RLY_SEPORT_SPARE2_LOOP,
	RLY_SEPORT_SPARE3_LOOP,
	RLY_SEPORT_ZM_RTS_LOOP,
	RLY_SEPORT_ZMODEM_LOOP,

	RLY_SSOM2_UART_RX_3V3,
	RLY_SSOM1_UART_RX_3V3,
	RLY_OUT_PUMP_TO232_3V3,
	RLY_OLC_TX_TO232_3V3,
	RLY_NONOLC_TX_TO232_3V3,
	RLY_SSOM2_UART_TX_3V3,
	RLY_SSOM1_UART_TX_3V3,
	RLY_SSOM_RESET_N,
};

enum iob_chann {
	IOB_DUMMY,

	//IO board 1,chan1~chan24, for Network Switch

	//IO board 2,chan25~chan48, 1.8V, P31&P32

	IOB_GSOM_CONFIG_1_A = 25,
	IOB_GSOM_CONFIG_2_A,
	IOB_GSOM_CONFIG_3_A,
	IOB_GSOM_CONFIG_4_A,
	IOB_GSOM_CONFIG_5_A,
	IOB_GSOM_CONFIG_6_A,
	IOB_GSOM_CTS_B2A_A_IN,
	IOB_GSOM_SOM1_ID_0,

	IOB_GSOM_CONFIG_1_B,
	IOB_GSOM_CONFIG_2_B,
	IOB_GSOM_CONFIG_3_B,
	IOB_GSOM_CONFIG_4_B,
	IOB_GSOM_CONFIG_5_B,
	IOB_GSOM_CONFIG_6_B,
	IOB_GSOM_RTS_A2B_B_IN,
	IOB_GSOM_SOM2_ID_1,

	IOB_GSOM_CTS_B2A_B_OUT,
	IOB_GSOM_RTS_A2B_A_OUT,
	IOB_GSOM_DLY_RST_A_OUT,
	IOB_GSOM_DLY_RST_B_OUT,
	IOB_GSOM_1_CRD_RX,
	IOB_GSOM_1_CRD_TX,
	IOB_GSOM_2_CRD_RX,
	IOB_GSOM_2_CRD_TX,

	//IO board 3,chan49~chan72, SPI&GPIO

	IOB_SPI_WR_START = 9,

	IOB_SPI_RD_START = 17,

	IOB_PUMP_TO_CRINDA,
	IOB_PUMP_TO_CRINDB,
	IOB_OLC_TX,
	IOB_NONOLC_TX,
	IOB_PCA9537_P3_PCNRST,
	IOB_USB_OVERCURR_FLAG,
	IOB_MODE_WD_ACTIVE,
	IOB_MIIMUX_WD_ACTIVE,
};

extern USART_CONFIG MRK_COMM_setting; //MERAK
extern USART_CONFIG GUI_COMM_setting; //GUI
extern USART_CONFIG DUT_COMM_setting; //DUT
extern USART_CONFIG LED_COMM_setting; //LED

extern void PowerCycle(void);
extern void Set_EtherMuxIO(U8 port_src, U8 port_dest);
extern BOOL TestExtIO(U8 chan, U8 desired_data);

extern void GUI_SendMessage(char *lpszFormat, ...);
extern void GUI_Process(void);

extern void TestItem_LED(U8 * test_result);
extern void TestItem_I2C(U8 * test_result);

extern BOOL Burn_I2cEEPROM(void);
extern void dbg(void);

extern int ComInit(USART_CONFIG *pconfig);
extern void Modules_Init(void);
extern void Modules_Config(void);

#endif /* APP_APP_H_ */
