/*
 * app.h
 *
 *  Created on: Jun 13, 2017
 *      Author: test
 */

#ifndef APP_APP_H_
#define APP_APP_H_

#include "includes.h"

#define PING_PORT_MAX	10

#define PING_PORT_SWITCH_P1		0
#define PING_PORT_BACKROOM		1	// Back Room

#define PING_PORT_SS2			9
#define PING_PORT_SS1			19	// independent

#define PING_PORT_FCT_HOMEPLUG	10

#define VLAN_ALL_LINK		1
#define VLAN_TRUTH_LINK		0

#define DUMY				0

enum relay_chann {
	RLY_DUMMY,
	//Relay board 1,chan1~chan24,
	RLY_24V_PPS=1,
	RLY_24V_VOLT,
	RLY_3V3_VOLT,
	RLY_5VPS_VOLT,
	RLY_VDDARM_VOLT,
	RLY_VDDSOC_VOLT,
	RLY_1V5_VOLT,
	RLY_1V1_VOLT,

	RLY_1V8_VOLT,
	RLY_5V_VOLT,
	RLY_1V35_VOLT,
	RLY_DDR_VTT_VOLT,
	RLY_DDR_VREF_VOLT,
	RLY_5V_USB_VOLT,
	RLY_7V5_VOLT,
	RLY_RESET_VOLT,

    RLY_VBAT_VOLT,
	RLY_D7_VOLT,
    RLY_PUMP1_VOLT,
	RLY_PUMP2_VOLT,
	RLY_D8_VOLT,
	RLY_D17_VOLT,
	RLY_D18_VOLT,
	RLY_D19_VOLT,
	//Relay board 2,chan24~chan48,
	RLY_24V_PPS_IPMED=25,
	RLY_24V_INPUT_IPMED,
	RLY_3V3_VOLT_IPMED,
	RLY_5VPS_VOLT_IPMED,
	RLY_VDDARM_VOLT_IPMED,
	RLY_VDDSOC_VOLT_IPMED,
	RLY_1V5_VOLT_IPMED,
	RLY_1V1_VOLT_IPMED,

	RLY_1V8_VOLT_IPMED,
	RLY_5V_VOLT_IPMED,
	RLY_1V35_VOLT_IPMED,
	RLY_DDR_VTT_VOLT_IPMED,
	RLY_DDR_VREF_VOLT_IPMED,
	RLY_5V_USB_VOLT_IPMED,
	RLY_24V_INPUT,
	RLY_D20_VOLT,

	RLY_ETH_P304A,
	RLY_ETH_J6101,
	RLY_ETH_J6102,
	RLY_ETH_J6103,
	RLY_ETH_J6104,
	RLY_ETH_J6201,
	RLY_ETH_J6202,
	RLY_ETH_J6203,
	//Relay board 3,chan49~chan72,
	RLY_DUT_DEBUG_TX=49,
	RLY_DUT_DEBUG_RX,
	RLY_LP_DUT_P303_1_FCT_P300_5,
	RLY_LP_DUT_P303_2_FCT_P300_4,
	RLY_LP_DUT_P300_1_FCT_P303_2,
	RLY_LP_DUT_P300_3_FCT_P303_1,
	RLY_LP_DUT_P300_4_FCT_P303_2,
	RLY_LP_DUT_P300_5_FCT_P303_1,

	RLY_FCT_P302B1_RS232IN,
	RLY_FCT_P302B5_RS232IN,
	RLY_FCT_P302B2_RS232OUT,
	RLY_FCT_P302B4_RS232OUT,
	RLY_DUT_SPEAKKE_P6901_1,
	RLY_DUT_SPEAKKE_P6902_1,
	RLY_DUT_SPEAKKE_P6901_2,
	RLY_DUT_SPEAKKE_P6902_2,

	RLY_LP_DUT_P300_4_DUT_P303_2,
	RLY_LP_DUT_P300_5_DUT_P303_1,
	RLY_RESET,
	RLY_P1_LOOPBACK,
	RLY_P2_LOOPBACK,
	RLY_3V3_LCD,
	RLY_BATTERY_SWITCH,
	RLY_PUMP_LOAD_SWITCH,
};

enum iob_chann {
	IOB_BOOT_CONFIG_0=1,
	IOB_BOOT_CONFIG_1,
	IOB_GSOM_CONFIG_2,
	IOB_GSOM_CONFIG_3,
	IOB_GSOM_CONFIG_4,
	IOB_GSOM_CONFIG_5,
	IOB_GSOM_CONFIG_6,
	IOB_GSOM_CONFIG_7,

	IOB_BOOT_CONFIG_8,
	IOB_BOOT_CONFIG_9,
	IOB_GSOM_CONFIG_10,
	IOB_GSOM_CONFIG_11,
	IOB_GSOM_CONFIG_12,
	IOB_GSOM_CONFIG_13,
	IOB_GSOM_CONFIG_14,
	IOB_GSOM_CONFIG_15,

	IOB_GSOM_CONFIG_16,
};

extern USART_CONFIG MRK_COMM_setting; //MERAK
extern USART_CONFIG GUI_COMM_setting; //GUI
extern USART_CONFIG DUT_COMM_setting; //DUT
extern USART_CONFIG LED_COMM_setting; //LED

extern void PowerCycle(void);
extern void Set_EtherMuxIO(U8 port_src, U8 port_dest);
extern BOOL TestExtIO(U8 chan, U8 desired_data);

extern void GUI_SendMessage(char *lpszFormat, ...);
extern void GUI_Process(void);


extern void TestItem_I2C(U8 * test_result);

extern BOOL Burn_I2cEEPROM(void);
extern void dbg(void);

extern int ComInit(USART_CONFIG *pconfig);
extern void Modules_Init(void);
extern void Modules_Config(void);
extern int Test_LED(void);
extern int Test_RegulatorLED(void);
extern int Test_ResetLED(void);
extern int Test_DismountLED(void);

#endif /* APP_APP_H_ */
